version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: quarkusDB
      POSTGRES_USER: sosamejia
      POSTGRES_PASSWORD: sosamejia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 